---
title: Biobotus
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _pages
  values:
    layout: page
- scope:
    path: _posts
  values:
    layout: post
- scope:
    path: _drafts
  values:
    layout: post
description: 'Accessible Digital Home Health Products

'
owner: Biobotus, LLC.
first_published: 2017
email: info@biobotus.com
baseurl: ''
url: http://biobotus.com
social:
  twitter: https://twitter.com/biobotus
  email: info@biobotus.com
compose:
  editor: subl
  extension: md
navlinks: bottom
works_in_progress: true
custom_extensions: false
permalink: "/:categories/:title.html"
markdown: kramdown
exclude:
- README
- s3_website.yml
include:
- _pages
- ".htaccess"
empty_array: []
highlighter: rouge
encoding: utf-8
gems:
- jekyll
- jekyll-email-protect
- jekyll-sitemap
- wdm
- listen
